---
driver:
  name: vagrant
  customize:
     memory: 4096
     cpuexecutioncap: 90
  network:
    - ["private_network", {ip: "192.168.10.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[docker-runtime::default]
      - recipe[docker-runtime::rabbitmq]
      - recipe[docker-runtime::memcached]
      - recipe[docker-runtime::redis]
    attributes:
